[package]
name = "av-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
av-transform = { path = "../av-transform" }
env_logger = "0.11.3"
log = "0.4.21"
serde = { version = "1.0.202", features = ["derive"] }
toml = "0.8.13"
